### ISSUE TITLE
A miscalculation

### ISSUE THREAD

**Issue by ramtob** [vasturiano/d3-binarytree#1]
Hello. I ran the following basic scenario on npm runkit:

const d3Binarytree = require("d3-binarytree")

const tree = d3Binarytree.binarytree([[1], [2], [3]]);

console.log(tree.find(2.3))

The result that I received was [3]. This is an error - should have been [2].

I ran a similar scenario on d3-quadtree:

var d3Quadtree = require("d3-quadtree")

const tree = d3Quadtree.quadtree([[1,0], [2,0], [3,0]]);

console.log(tree.find(2.3,0))

Here I received the correct value [2, 0]

**Comment by vasturiano** [comment]
@ramtob thanks for spotting this! There was indeed a miscalculation in the distance between the input and the nodes that was generating negative distances for nodes above the input. This has been fixed in `v0.1.2`: [caf508a](https://github.com/vasturiano/d3-binarytree/commit/caf508aca4f91bc06009287a964e52988a6ca85d#diff-b1b9bf02ff07ad669cc803729b4bd013)
